#!/usr/bin/env sh
set -o errexit

installDeps() {
    apk add --quiet --update tzdata
}

setTimezone() {

    local TZ_FILE="/usr/share/zoneinfo/${1}"

    if [ ! -e "${TZ_FILE}" ]; then
        echo "ERROR: Invalid timezone supplied. See: https://goo.gl/uy1J6q"; exit 1
    fi

    cp ${TZ_FILE} /etc/localtime
    echo "${1}" > /etc/timezone

}

cleanup() {
    apk del --quiet tzdata && rm -rf /var/cache/apk/*
}


main() {

    if [ -z "${1}" ]; then
        echo "ERROR: Must supply timezone. See: https://goo.gl/uy1J6q"; exit 1
    fi

    # Install tzdata and set timezone
    trap cleanup INT TERM EXIT
        installDeps && setTimezone ${1}
    trap - INT TERM EXIT

    cleanup

    echo -n "Timezone sucessfully updated. Current time is now: " && date

}

main ${1}
